hash-format = "sha256"

[[files]]
file = "config/yosbr/config/skinrestorer/config.json"
hash = "156e0d4365e3cfbb35c7748e4531a386b410685bd57967bacf9bb2dbb24a2d96"

[[files]]
file = "config/yosbr/icon.png"
hash = "247dfe5bf4e6c33acadbc90e91a28d74ea25f0c1471264de2ddc0ca1a6ee7bbd"

[[files]]
file = "config/yosbr/options.amecsapi.txt"
hash = "a0c1b00caf2e439e9d00644c1e31655ae32daac7af97cb25096d11ff33b7126f"

[[files]]
file = "config/yosbr/options.txt"
hash = "6f1b0dc24fb1ba2532569f8c10f3789085f72ada6d099cb9f291e28352b98e71"

[[files]]
file = "import-modlist.nu"
hash = "bb56a303cf7c6927f445be87960931637a8aef8c5942c3a7368d757bf467c0b3"

[[files]]
file = "modlist"
hash = "cfbfc2086813c71e550814c6bd4b9e29fd49d504a15157bae05cfb5cf886a104"

[[files]]
file = "mods/accessories-tc-layer.pw.toml"
hash = "448122a913a9588559026b8974a9d1cf75996fbf637c716ab2535b8ccf461cb5"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
hash = "35228989dbf447ed8a124fda344ef42720b7811d1326cb3e7373cc06f72d63fc"
metafile = true

[[files]]
file = "mods/accessorify.pw.toml"
hash = "41fc9132cbeba0d3a14159e2f36be7e2f7037bc04bb121711d89028d06494562"
metafile = true

[[files]]
file = "mods/actually-harvest.pw.toml"
hash = "e387aa578317fee54ee2af339b5af2b851d5a89c22bd023d8beb2adf4bd7c873"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
hash = "6317bd1e6013059a52574d7002e744cd1d662ba345d019d75e37d384fd6060b0"
metafile = true

[[files]]
file = "mods/amecs.pw.toml"
hash = "1e5b00de09f3382cb89564dca455b0d547855c09d8d28d2e98e47d95fabcaeff"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "5b332b628f2bbb11afdc82f4a9d27ca3afde5ad2d21c590af5c7a080c2aa9dfa"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/autoslabs.pw.toml"
hash = "8c42b3274f3a13c7d064cf1c3d660863f70e42c45325bebd8349993555b263a6"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "71dc04da11ad8f4a5d88db5505132a654ce033f05dc2fa4bb7aa28a42762086f"
metafile = true

[[files]]
file = "mods/better-climbing.pw.toml"
hash = "9c19d98d506afb126972e894249db28bd404540146d45db2e66a1c20aaf9fed3"
metafile = true

[[files]]
file = "mods/better-ladders.pw.toml"
hash = "681745d81e0d7f079f80242d8257a9711892725b041b183004c510956b612ffe"
metafile = true

[[files]]
file = "mods/boids.pw.toml"
hash = "d552818d69391de8a10945619b9e50ba25df1081d5d31a8fbd23d644fbb56a5c"
metafile = true

[[files]]
file = "mods/building-wands.pw.toml"
hash = "d250a791b3ec9538036276fde244293c9c6d1854d6073d13f731f0fe36c73ff7"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "0cc9069aeee558e036c7afd064d37d9f468ea1138705da0fe4aad64d95312f79"
metafile = true

[[files]]
file = "mods/camerapture.pw.toml"
hash = "d4385c21ca7b5fd584baed3a1c30b06c0839d345fb0ad7efb7333fd929e81e19"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "5ba003768a235ab0d811218191166f9aefa4c9a2509341fbba1efd80e18d3676"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "15385164e2cd07cce7493a10d6d87df5c7bce587a866613126be3b54b6b28fc7"
metafile = true

[[files]]
file = "mods/connectiblechains.pw.toml"
hash = "75eb7e12f9b31307fe5ab5d6d4327d794c62d43cc729a4d0587d5a6ffed4a2b5"
metafile = true

[[files]]
file = "mods/crafteble-nametags.pw.toml"
hash = "69060449628d43f108449ed9b4729e1c5c76c8101e8d589a0fd0c97ea25b7d7c"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "6ec7fc70c84dc7f7f4578a85480264d82336d64ac0d8c95c0fcc55d350f64ab7"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "5944ed5a779d142aea9ccd8c466a20fa3d9233a29f2be1e5ae54fc15f5edd57e"
metafile = true

[[files]]
file = "mods/data-anchor.pw.toml"
hash = "d3f1d70958b437490de965ab3e9f2b70a04900c576ccfcc29905aea078c67251"
metafile = true

[[files]]
file = "mods/dcwa.pw.toml"
hash = "3f80cbcbccd66c8d1c0fe03ab51c5b2bb4a31e3bcece2638f0d4b1d48223d322"
metafile = true

[[files]]
file = "mods/draggable-lists.pw.toml"
hash = "bfe939f563e561df6410a82e9f36ec3793634e470c9b729088072ff8824018ac"
metafile = true

[[files]]
file = "mods/dramatic-doors.pw.toml"
hash = "8143c63aa2e53fd78ea83eddba9cfaa4c036141aae6604eb01d8f82dc5d03c99"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "0bcc0df994ebbe98efc2f87c653cd0ae0a81bb0ca47b5adacba0974c5c6406c5"
metafile = true

[[files]]
file = "mods/early-loading-screen.pw.toml"
hash = "cb5d0f9fdc6224769a0339389816936f40e0a61b408e5e05d5088f696a799f37"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "fec1ffa03b4d62e47be25512840490844fc383cf82d2ad35345b2f87a21e8228"
metafile = true

[[files]]
file = "mods/enchancement.pw.toml"
hash = "54ed85b42559773c1d59f774b7d1e17938232b97432b20469ead70d69673b6ab"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7eefb0f3d1b793f7dc57ee7cf368d055c9b1bf3556f61179f38f1c49c163c1bd"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fairy-lights-fabric.pw.toml"
hash = "9d38598102668a37787549c12ee234cedcac450b5b78d183e8e076e78da582d0"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "adea09f1e1b05da68cf7407992a9391b15985acf5465a888e54ae076dbd543ab"
metafile = true

[[files]]
file = "mods/fossils-and-archeology-revival.pw.toml"
hash = "bc8812a2e90bcead8b081be6003c606a78fa0d38a932362b51a7ce35a3ef1362"
metafile = true

[[files]]
file = "mods/frozenlib.pw.toml"
hash = "41e364c29ac783e302b4dfd7e1832ca3d814870acdfc4591e4791eb80ce445f7"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "ac04594aa529b7f383fc5c8fc942cd6a2985852882d06b3f0f0743a9415afd82"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "b534fbebf760ee1f9382d18e22450ef006d67b50bd9043cedaa9f5c31a501041"
metafile = true

[[files]]
file = "mods/gardeners-dream.pw.toml"
hash = "1028e77041093958ffaf1156a4e4c63c8dd82fa378066ead2dc67dc7a9c25e3e"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "21d2df923fa369d69a40d69f6466153146bf403367430eaeb2569c1554857df8"
metafile = true

[[files]]
file = "mods/grind-enchantments.pw.toml"
hash = "0126e37774a89e6089826219d27b65f4d11b48fe0b352c701b7e2371c590b08c"
metafile = true

[[files]]
file = "mods/herdspanic.pw.toml"
hash = "a4540dd8807f53182939edae5f114e801097433370a3b11a3c19a5e940d7b6c1"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "d9d01681616a8bdb45bbdd0a053b87153bbb77a5ef997325be0b3dc10b7f8979"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "67b0b2bd471fc2393c7c8e95cae5ae6031e621d11f5e253c07a4427857f1a2bd"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/inventory-management.pw.toml"
hash = "5f74332db22a2eda4c05a7469cf57af07438ccb3fbb016b1ba9131b7164e7a1a"
metafile = true

[[files]]
file = "mods/jade-addons-fabric.pw.toml"
hash = "b28167f09bbcaca3fee27d748191ed19ce37b9382bb4ae693a20f415f80ed305"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8508e46b7e272d79dc6b3cc0149f9fd132c701369bcb2abb5c35da3ed92b27fb"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "6b986485b44e2007fc69334325f45ad1a4ad1d09d7f7814b1dbc443f171abbd1"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c8695e51366b601c5e9118a5d5650d234cc25fc8d1f90ebd186c17c199ba7fca"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "62b5f6133f799c95d48314eef3e353b8689477f075e9f604a2566de03d593563"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "bc91fa90e9f26f3ff3690c1a508647a162cd63dc36d815b8af0d6f5e01e5ecbf"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "866baeb7e9917b92825ddbcf4d113648a6662b5214e078b29c327ff97d0e2774"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "d8a2ea4edf1c55f6fe01cbcc220543f056b91c0d79512e96df22e4259b7c5777"
metafile = true

[[files]]
file = "mods/more-hitboxes.pw.toml"
hash = "6df5965c9c14d14b1cd89c8c2f1ca162a9742cab21dbb48d38f1e21daca1ba6e"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "9ff690ee32105d52a646a76f48371ccbe1958aff274511ca71fb44099ebc7107"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/name-tailor.pw.toml"
hash = "b8b99d3e6a08aea28d9bd6621736de111f8ce60488096fee55ca6113fb792683"
metafile = true

[[files]]
file = "mods/niftycarts.pw.toml"
hash = "85403dfbcff240580a8630397c8a2da2c9a006fc3e4236948983520121c4620d"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings.pw.toml"
hash = "da9ac20bdc1caa50ebec291429638780924e8a5060ec39abe085c7e6182b3a6f"
metafile = true

[[files]]
file = "mods/omnicrossbow.pw.toml"
hash = "8bec497ad1489078a868e143aaa1a21504c6c9272766a6d7ffd6423f00ac80c1"
metafile = true

[[files]]
file = "mods/omnicut-better-wood-stone-cutter.pw.toml"
hash = "d28f5b02438d59d3b0374dc136b197608d7f100dac59f3c253c6151a1fc0f5f8"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "3f8f31eed84a4a29618cf04e300ea02ace03095ff4e8c4c23ec92f09849ed1f0"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
hash = "5beb6ef32d80ab0550baad15f1fd78f2c6168fcce4a18e14e23c47a1cc8ed099"
metafile = true

[[files]]
file = "mods/player-locator-plus.pw.toml"
hash = "7bb62be8c97ff5bad23337b066a4d1f491226cd840be3cc10489480312dd9eb9"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8293786ca23e23e7dd04d60d666f34145a00229a5959f7a1962995654cacdf1f"
metafile = true

[[files]]
file = "mods/radiant-gear.pw.toml"
hash = "d7f20eaa93687d913a5a378a51964b34a77374f0b3961514b9f8715e9fe120bf"
metafile = true

[[files]]
file = "mods/reacharound.pw.toml"
hash = "c08dcea37c03dcb5cfad9d3d14f5e885995cf9bb74975244781e1354c937afa7"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4a7d1e46795d2d83b18db85d8dbc63740a1d337e12d2b9e550378de59f2b23ab"
metafile = true

[[files]]
file = "mods/rotten-to-leather.pw.toml"
hash = "0b713337101e15001d5c87bdf9752fbed902f4bd232539719d288bb0cde10ab5"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "83164a6af3923e28cadf9d404f059bf74aa4f0842fc1ca0f6e7cf1e686044875"
metafile = true

[[files]]
file = "mods/simple-belt-lanterns.pw.toml"
hash = "15a808dcac3a064074b22bde2ddf939883cb754cfce97abe5628b75078b15bdc"
metafile = true

[[files]]
file = "mods/simple-copper-pipes.pw.toml"
hash = "ac586a552c30ff577efd8f843350304f112efb133062ca7a357a31628a04368f"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "62a6f5a489aa45fda94386b89a75485312338261998ddbb2d11316f595d2c38f"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8ad07191dfdea31249b4416a390c1cdf1d4ff1938cf9f8a617f98f7a08c5356c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-(unoffical-fabric-port).pw.toml"
hash = "0238d3e484f1829aaabb3b2482e528e192f3124fad89d81f43d7b60406e17d71"
metafile = true

[[files]]
file = "mods/sophisticated-core-(unofficial-fabric-port).pw.toml"
hash = "7bbc2d52041fddcb8572b50cbe39cdff6f83060da3b16eb965d882bb7ee852c3"
metafile = true

[[files]]
file = "mods/sophisticated-storage-(unofficial-fabric-port).pw.toml"
hash = "bad699bcd2c76c29b41ef64c812cf90dec0f35040e315b846c8146641d5a0d99"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "98553c2d49ef3a888954f24b7c49fe3442c01fd4fc1f1ed52c5898ed29d29d3b"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
hash = "116f803a2b3c68c5b0b7bfbad1fd9072ed3df78a1dcdfa8c48f70e5ef450f620"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "3135bb6ec401e951d248de79dbdf40608e362e64b89fe9e7d2e74399f3b49375"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "b3ae602303fd717bff2344bfb89aa427e2b4a1ab5fffdcc25183b22102c492df"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "f26fb3886f4c53b3284264cacfebb4bfe68a189205363e8e406896c847c1e0ea"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "ee103bf45111c2cd7ea2d9b31087867dd4b0d07a4b7dad7b138a4ae506127b37"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "7b7108d879e1e1c141b24d0d8fa268a6bbcd5c227875d156fcc62c3beec55f63"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "df71b5d7427e9a508e9f298b5cdec84aa8c4fcb584beb0d16d86efb9d47b3bcd"
metafile = true

[[files]]
file = "mods/treechop.pw.toml"
hash = "d4973af17081ec2f1d5aabad778331459612fc95617cda5fbcafa79ea9384c43"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "ffdb79f5bc29f990e5889f5d159a043c7046b8cd8d79f17f54b44d7ccc2b242a"
metafile = true

[[files]]
file = "mods/vanillabackport.pw.toml"
hash = "e17c2c575f2db23bb4e6cb7035093ec67f0c2189e7e3026075794579c6a05fd4"
metafile = true

[[files]]
file = "mods/vanillaskyvillages.pw.toml"
hash = "bc8915e764d4f76ea60773975b3d2d22857f39b4508f615e3ccd856884eb53b6"
metafile = true

[[files]]
file = "mods/vb-mob-variants-compat.pw.toml"
hash = "ce2c77ea4776ab4945d50f8eb286d673abb946320d2aa8a3b956b58e4353fc50"
metafile = true

[[files]]
file = "mods/via-romana.pw.toml"
hash = "d71a74b5d87f094483460c4140a1ba5e7a73190097b9306848b25402810981fe"
metafile = true

[[files]]
file = "mods/wi-zoom.pw.toml"
hash = "44d8c335a317321656239b2dd2a90ade818d71f6f3b2de46467feb5442677c52"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "3968601926c3f69b5605ca7af9c3fcf3fd030f89a7a1d25a9b22fb48b00b6c02"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "8549141793a632e91039e30d45cf665bcac94cacd7b4d591cb5bca75557b73e5"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "packwiz-installer-bootstrap.pw.toml"
hash = "66fd4a47f4eb3fc7b0e487b0fafc998f009e889188bcc5a609d04c2ab97e369f"
metafile = true
